### ISSUE TITLE
Alacritty as default terminal

### ISSUE THREAD

**Issue by ThSGM** [willbchang/alfred-run-in-terminal#1]
Do you know if it's possible to use Alacritty as the default terminal? i.e. the command would ne: 

`ruby script.rb "$1" "Alacritty"`

It doesn't seem to work for me but it could be something I've done wrong.

**Comment by weierz** [comment]
I think Alacritty has problem with applescript. Ref: https://github.com/alacritty/alacritty/issues?q=applescript

Discussions on this issue might have valid solutions: https://github.com/alacritty/alacritty/issues/2638

A pull request is also welcome. ;)
